version: '2'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: /gunicorn.sh
    volumes:
      - .:/app

  nginx:
    build: ./compose/nginx
    depends_on:
      - django
    volumes_from:
      - django
    ports:
      - "0.0.0.0:80:80"